config/routes.rb
Comapp::Application.routes.draw do

  resources :ratings

  resources :posts

  resources :consultants

  resources :subjects

  resources :groups

  resources :accounts

  devise_for :users
  delete "users/sign_out"

  root :to => "home#index"
  get "home/index"

end

app/models/consultant.rb
class Consultant < ActiveRecord::Base
  belongs_to :group
  has_many :posts
    
end

app/controllers/consultants_controller.rb
class ConsultantsController < ApplicationController
  
  before_filter :authenticate_user!
    
  # GET /consultants
  # GET /consultants.json
  def index
#    @consultants = Consultant.where("group_id = ?", current_user.account.group.id)
    @consultants = Consultant.all   
    groups = current_user.account.groups
    @consultants = Array.new
    groups.each do |group|
      @consultants.concat(group.consultants)
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @consultants }
    end
  end

  # GET /consultants/1
  # GET /consultants/1.json
  def show
    @consultant = Consultant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @consultant }
    end
  end

  # GET /consultants/new
  # GET /consultants/new.json
  def new
    @groups = Group.all
    @consultant = Consultant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @consultant }
    end
  end

  # GET /consultants/1/edit
  def edit
    @consultant = Consultant.find(params[:id])
  end

  # POST /consultants
  # POST /consultants.json
  def create
    @consultant = Consultant.new(params[:consultant])

    respond_to do |format|
      if @consultant.save
        format.html { redirect_to @consultant, notice: 'Consultant was successfully created.' }
        format.json { render json: @consultant, status: :created, location: @consultant }
      else
        format.html { render action: "new" }
        format.json { render json: @consultant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /consultants/1
  # PUT /consultants/1.json
  def update
    @consultant = Consultant.find(params[:id])

    respond_to do |format|
      if @consultant.update_attributes(params[:consultant])
        format.html { redirect_to @consultant, notice: 'Consultant was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @consultant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultants/1
  # DELETE /consultants/1.json
  def destroy
    @consultant = Consultant.find(params[:id])
    @consultant.destroy

    respond_to do |format|
      format.html { redirect_to consultants_url }
      format.json { head :ok }
    end
  end
end

app/helpers/consultants_helper.rb
module ConsultantsHelper
end

app/views/consultants/_form.html.erb
<%= form_for(@consultant) do |f| %>
  <% if @consultant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@consultant.errors.count, "error") %> prohibited this consultant from being saved:</h2>

      <ul>
      <% @consultant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br />
    <%= f.select :group_id, options_from_collection_for_select(@groups, "id", "name") %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/consultants/edit.html.erb
<h1>Editing consultant</h1>

<%= render 'form' %>

<%= link_to 'Show', @consultant %> |
<%= link_to 'Back', consultants_path %>

app/views/consultants/index.html.erb
<h1>consultants</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Group</th>
		<th>Posts</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @consultants.each do |consultant| %>
  <tr>
    <td><%= consultant.name %></td>
    <td><%= consultant.group.name %></td>
    <td><%= consultant.posts.count %></td>
    <td><%= link_to 'Show', consultant %></td>
    <td><%= link_to 'Edit', edit_consultant_path(consultant) %></td>
    <td><%= link_to 'Destroy', consultant, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Consultant', new_consultant_path %>

app/views/consultants/new.html.erb
<h1>New consultant</h1>

<%= render 'form' %>

<%= link_to 'Back', consultants_path %>

app/views/consultants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @consultant.name %>
</p>

<p>
  <b>Group:</b>
  <%= @consultant.group_id %>
</p>

<p>
  <b>Posts:</b>
  <%= link_to "#{@consultant.posts.count}", posts_path  %>
</p>

<%= link_to 'Edit', edit_consultant_path(@consultant) %> |
<%= link_to 'Back', consultants_path %>