config/routes.rb
Comapp::Application.routes.draw do

  resources :ratings

  resources :posts

  resources :consultants

  resources :subjects

  resources :groups

  resources :accounts

  devise_for :users
  delete "users/sign_out"

  root :to => "home#index"
  get "home/index"

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :account
  belongs_to :group
  has_many :posts
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  
  before_filter :authenticate_user!
  
  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subjects }
    end
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    @subject = Subject.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/new
  # GET /subjects/new.json
  def new
    @accounts = Account.all
    @groups = Group.all
    @subject = Subject.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/1/edit
  def edit
    @subject = Subject.find(params[:id])
    @accounts = Account.all
    @groups = Group.all
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(params[:subject])

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render json: @subject, status: :created, location: @subject }
      else
        format.html { render action: "new" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subjects/1
  # PUT /subjects/1.json
  def update
    @subject = Subject.find(params[:id])

    respond_to do |format|
      if @subject.update_attributes(params[:subject])
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url }
      format.json { head :ok }
    end
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
	<div class="field">
    <%= f.label :account_id %><br />
    <%= f.select :account_id, options_from_collection_for_select(@accounts, "id", "name") %>
  </div>
	<div class="field">
    <%= f.label :group_id %><br />
    <%= f.select :group_id, options_from_collection_for_select(@groups, "id", "name") %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<h1>Subjects</h1>

<table>
  <tr>
    <th>Name</th>
		<th>Account</th>
		<th>Group</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subjects.each do |subject| %>
  <tr>
    <td><%= subject.name %></td>
		<td><%= subject.account.name %></td>
		<td><%= subject.group.name %></td>
    <td><%= link_to 'Show', subject %></td>
    <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
    <td><%= link_to 'Destroy', subject, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @subject.name %>
</p>

<p>
  <b>Account:</b>
  <%= @subject.account.name %>
</p>

<p>
  <b>Group:</b>
  <%= @subject.group.name %>
</p>

<p>
	<b>Posts:</b>
	<%= @subject.posts.count %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %>

<p>--------------------------------------------------------------------------------------</p>

<h3>Consultants</h3>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subject.group.consultants.each do |consultant| %>
  <tr>
    <td><%= link_to consultant.name, consultant %></td>
  </tr>
<% end %>
</table>